BackendBundle\Entity\Game:
    type: entity
    table: game
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        winning_points:
            type: integer
        created_at:
            type: datetime
        finished_at:
            type: datetime
            nullable: true
    manyToOne:
        game_state:
            targetEntity: GameState
            joinColumn:
                game_state_id:
                    referencedColumnName: id
        game_winner:
            targetEntity: Team
            joinColumn:
                game_winner_id:
                    referencedColumnName: id            
    manyToMany:
        teams:
          targetEntity: Team
          joinTable:
            name: game_teams
            joinColumns:
                game_id:
                    referencedColumnName: id
            inverseJoinColumns:
                group_id:
                    referencedColumnName: id
          cascade: [persist, remove]
          

