BackendBundle\Entity\Game:
    type: entity
    table: game
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        winning_points:
            type: integer
        created_at:
            type: datetime
    manyToMany:
        teams:
          targetEntity: Team
          joinTable:
            name: game_teams
            joinColumns:
                game_id:
                    referencedColumnName: id
            inverseJoinColumns:
                group_id:
                    referencedColumnName: id
          cascade: [persist, remove]
          

