BackendBundle\Entity\Team:
    type: entity
    table: team
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        created_at:
            type: datetime            
    manyToMany:
        users:
          targetEntity: User
          joinTable:
            name: team_users
            joinColumns:
              team_id:
                referencedColumnName: id
            inverseJoinColumns:
              user_id:
                referencedColumnName: id
          cascade: [persist, remove]

