services:
#    backend.example:
#        class: BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
   BackendBundle\DataFixtures\UserFixture:
        tags: ['doctrine.fixture.orm']
